
version: 2
sources:
  - name: bq_source1
    database: edwhsk1
    schema: dbt_test
    tables:
      - name: orders
models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
      config:
        materialized: table
        